# Generated by Django 5.1 on 2024-09-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
