# Generated by Django 5.1 on 2024-09-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_age_user_password_remove_user_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='person',
        ),
    ]
