# Generated by Django 5.1 on 2024-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blackmyt_cyberpunk_doom_minecrafe_spiderman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
