# Generated by Django 5.1 on 2024-10-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackmyt',
            name='score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cyberpunk',
            name='score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='doom',
            name='score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='minecrafe',
            name='score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='spiderman',
            name='score',
            field=models.CharField(max_length=2),
        ),
    ]
